### PR TITLE
add phantomjs

### LINKED ISSUE #22: for me to run locally I need the phantomjs gem
otherwise I get:

```
Could not find an executable ["phantomjs"] on your path. (Cliver::Dependency::NotFound)
./features/step_definitions/joining_steps.rb:6:in `/^I visit the page for an event$/'
features/joining_an_event.feature:15:in `Given I visit the page for an event'
```

I think that the phantomjs gem is the best way to manage this dependency, but am totally open to suggestions ...

### PR DESCRIPTION
**Pull request by tansaku**
fixes #22

### CODE REVIEW

**Comment by tansaku** [comment]
this won't work for me locally till I fiddle with the poltergeist config - it'll need:

```
Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, js_errors: false,
                                    phantomjs: Phantomjs.path,
                                    phantomjs_options: ['--ssl-protocol=tlsv1.2', '--ignore-ssl-errors=yes'])
end
```

**Comment by tansaku** [comment]
now tests are passing for me locally ...

**Comment by arreche** [comment]
👍

**Review by mattlindsey — APPROVED** [review]
Looks good. Works for me.

**Pull request merged**
